<a href="https://colab.research.google.com/github/najahtulakma/Finlatics/blob/main/The%20Data%20Toolkit%20%E2%80%94%20NumPy%2C%20Pandas%2C%20Statistics%20%26%20Text%20Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# The core data stack - you'll use these every single day
import numpy as np          # Numerical computing - the foundation
import pandas as pd         # Data manipulation - the workhorse
import matplotlib.pyplot as plt  # Visualization - the storyteller
import seaborn as sns       # Statistical visualization - the artist
from sklearn import *       # Machine learning - the predictor


In [ ]:
!pip install numpy

In [ ]:
# Python list approach
python_list = [1, 2, 3, 4, 5]
# To multiply each element by 2, you need a loop or list comprehension
result = [x * 2 for x in python_list]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
var_a = 3
print( var_a * 2)

6


In [ ]:
import numpy as np

# NumPy approach
numpy_array = np.array(python_list)
result = numpy_array * 2
print(result)

[ 2  4  6  8 10]


In [ ]:
[5, True, "Test"]

In [ ]:
# From a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2D array (matrix) - a list of lists
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

# 3D array
arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(arr3)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Integer array
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)  # int64

# Float array
arr_float = np.array([1.5, 2.7, 3.2])
print(arr_float.dtype)  # float64

# Specifying dtype explicitly
arr = np.array([1, 2, 3], dtype='float32')
print(arr)        # [1. 2. 3.]
print(arr.dtype)  # float32

# Boolean array
arr_bool = np.array([True, False, True])
print(arr_bool.dtype)  # bool


int64
float64
[1. 2. 3.]
float32
bool


In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim)   # 1          — number of dimensions
print(arr_1d.shape)  # (5,)       — size along each dimension
print(arr_1d.size)   # 5          — total number of elements

# 2D array
arr_2d = np.array([
      [1, 2, 3],
      [4, 5, 6]
])
print(arr_2d.ndim)   # 2          — two dimensions (rows & columns)
print(arr_2d.shape)  # (2, 3)     — 2 rows, 3 columns
print(arr_2d.size)   # 6          — total elements

# 3D array
arr_3d = np.array([
    [[1, 2, 3], [3, 4, 3]],
    [[5, 6, 3], [7, 8, 3]]
  ])
print(arr_3d.ndim)   # 3
print(arr_3d.shape)  # (2, 2, 3)
print(arr_3d.size)   # 12


1
(5,)
5
2
(2, 3)
6
3
(2, 2, 3)
12


**Think of it this way:**
- 1D = a row of numbers (like a list)
- 2D = a table (rows and columns)
- 3D = a stack of tables (like an Excel workbook with sheets)

### Reshaping Arrays

In [ ]:
# Create a 1D array with 12 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape into 3 rows x 4 columns
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Reshape into 2 rows x 6 columns
reshaped2 = arr.reshape(2, 6)
print(reshaped2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# Use -1 to let NumPy calculate one dimension automatically
reshaped3 = arr.reshape(4, -1)  # 4 rows, NumPy figures out 3 columns
print(reshaped3.shape)  # (4, 3)


(4, 3)


In [ ]:
# Flatten back to 1D
flat = reshaped.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np

# arange — like Python's range(), but returns an array
arr = np.arange(0, 10, 2)  # start, stop (exclusive), step
print(arr)  # [0 2 4 6 8]

arr = np.arange(1, 11)  # 1 to 10
print(arr)  # [ 1  2  3  4  5  6  7  8  9 10]

# linspace — evenly spaced numbers between start and stop (inclusive)
arr = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print(arr)  # [0.   0.25 0.5  0.75 1.  ]

arr = np.linspace(0, 100, 11)
print(arr)  # [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

# zeros — array filled with 0s
arr = np.zeros(5)
print(arr)  # [0. 0. 0. 0. 0.]

arr = np.zeros((3, 4))  # 3x4 matrix of zeros
print(arr)

# ones — array filled with 1s
arr = np.ones((2, 3))
print(arr)
# [[1. 1. 1.]
#  [1. 1. 1.]]

# full — array filled with a specific value
arr = np.full((3, 3), 7)
print(arr)
# [[7 7 7]
#  [7 7 7]
#  [7 7 7]]

# eye — identity matrix (1s on diagonal)
arr = np.eye(4)
print(arr)


[0 2 4 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np

# Random float between 0 and 1
print(np.random.rand())        # e.g., 0.5488135

# Array of random floats
print(np.random.rand(5))       # 5 random floats
print(np.random.rand(2, 3))    # 2x3 matrix of random floats

# Random integers
print(np.random.randint(1, 10))         # one random int between 1-9
print(np.random.randint(1, 100, 5))     # 5 random ints between 1-99
print(np.random.randint(1, 7, (3, 3)))  # 3x3 matrix, values 1-6

# Random from normal distribution (mean=0, std=1)
print(np.random.randn(5))              # 5 values from standard normal
print(np.random.normal(50, 10, 1000))  # mean=50, std=10, 1000 values

# Random choice from an array
arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr))        # pick one random element
print(np.random.choice(arr, 3))     # pick 3 random elements

# Shuffle — modifies array in place
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)  # e.g., [3, 1, 5, 2, 4]




0.3609722978852241
[0.16876923 0.0602274  0.35034869 0.39831672 0.99855905]
[[0.91630198 0.22982618 0.39963675]
 [0.31983565 0.54657808 0.07495878]]
6
[78 52 56 81 41]
[[3 3 5]
 [1 6 1]
 [3 1 2]]
[-0.46562514  0.45760999 -0.56068261 -1.47591143 -0.48705097]
[53.95967526 55.72527658 61.75675474 52.37851423 34.68836728 44.60539645
 50.48214908 51.75621293 44.55894908 44.74252873 53.39738104 32.14431917
 54.25068438 41.80877349 52.36840908 26.09790561 48.98054035 53.8132808
 58.09832518 45.2988067  45.39980269 36.51903308 37.08769325 43.93884959
 56.6230737  36.0807035  53.4377318  38.17751211 68.08609905 55.7306384
 43.19976921 44.89497809 42.20072586 48.36153826 56.3981285  59.50966442
 53.05199327 47.15529828 64.78061925 58.05256499 46.10674808 48.3816249
 44.06885675 64.76848397 45.41666307 38.26318699 55.38873432 56.57889939
 60.05725998 42.50558474 58.47381115 37.17267016 56.50641337 70.95978484
 40.40000091 36.24824165 40.42450285 30.74231898 46.26846061 51.27628385
 46.61844179 53

In [ ]:
print(np.random.rand(5))

[0.27262068 0.81796428 0.97208414 0.9916215  0.30527436]


In [ ]:
# Seed — for reproducible results
np.random.seed(42)
print(np.random.rand(5))  # Always gives the same 5 numbers

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Single element (0-indexed)
print(arr[0])    # 10  — first element
print(arr[4])    # 50  — fifth element
print(arr[-1])   # 100 — last element
print(arr[-3])   # 80  — third from the end

10
50
100
80


In [ ]:
# Slicing: arr[start:stop:step] — stop is EXCLUSIVE
print(arr[2:6])    # [30 40 50 60]
print(arr[:5])     # [10 20 30 40 50]   — first 5
print(arr[5:])     # [60 70 80 90 100]  — from index 5 onwards
print(arr[::2])    # [10 30 50 70 90]   — every other element
print(arr[::-1])   # [100 90 80 ... 10] — reversed


[30 40 50 60]
[10 20 30 40 50]
[ 60  70  80  90 100]
[10 30 50 70 90]
[100  90  80  70  60  50  40  30  20  10]


### 2D Array Indexing

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Single element: arr[row, column]
print(arr[0, 0])    # 1   — first row, first column
print(arr[1, 2])    # 7   — second row, third column
print(arr[2, -1])   # 12  — last row, last column

# Entire row
print(arr[0])        # [1 2 3 4]  — first row
print(arr[1, :])     # [5 6 7 8]  — second row (explicit)

# Entire column
print(arr[:, 0])     # [1 5 9]    — first column
print(arr[:, -1])    # [4 8 12]   — last column

# Sub-matrix (slicing rows AND columns)
print(arr[0:2, 1:3])
# [[2 3]
#  [6 7]]

# Multiple specific rows
print(arr[[0, 2]])   # first and third rows


1
7
12
[1 2 3 4]
[5 6 7 8]
[1 5 9]
[ 4  8 12]
[[2 3]
 [6 7]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
